version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiapx
    ports:
      - "5432:5432"
    volumes:
      - ./db/scripts.sql:/docker-entrypoint-initdb.d/scripts.sql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  video-processor-service:
    build:
      context: ./video-processor-service
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=aj6I4zJ4jxT1Vsk8q3!q8*2%T91m4G5n7w1B9Xk2tR6sE0V1

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "5050:5000"
    depends_on:
      - postgres
      - rabbitmq
    command: ["/wait-for-it.sh", "postgres:5432", "--", "npm", "run", "start"]

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "3200:3200"
    depends_on:
      - postgres
    command: ["/wait-for-it.sh", "postgres:5432", "--", "npm", "run", "start"]

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3100:3100"
    environment:
      - JWT_SECRET=aj6I4zJ4jxT1Vsk8q3!q8*2%T91m4G5n7w1B9Xk2tR6sE0V1
    depends_on:
      - auth-service
      - video-processor-service
      - notification-service
