name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Instalar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Configurar Docker
        run: |
          docker-compose build

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Instalar dependências
        working-directory: ./notification-service
        run: |
          npm install

      - name: Executar testes
        working-directory: ./notification-service
        run: |
          npm run test

  rabbitmq-test:
    name: Test RabbitMQ Message
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Instalar dependências
        working-directory: ./notification-service
        run: |
          npm install

      - name: Testar envio de mensagem para RabbitMQ
        working-directory: ./notification-service
        run: |
          node test/sendMessage.ts